### ISSUE TITLE
"支持了64位编译"后还支持32位吗？

### ISSUE THREAD

**Issue by kingyueyang** [bjqiwei/chilli#1]

**Comment by bjqiwei** [comment]
还支持32位编译



qiweibo1984@126.com
 
发件人： YangYue
发送时间： 2018-09-07 09:30
收件人： bjqiwei/chilli
抄送： Subscribed
主题： Re: [bjqiwei/chilli] "支持了64位编译"后还支持32位吗？ (#1)
Closed #1.
